#!/bin/bash

export PROJECT_NAME="team_campaign"

docker-compose --compatibility --project-directory . --project-name "${PROJECT_NAME}" --file "docker-compose.yml" down

docker-compose --compatibility --project-directory . --project-name "${PROJECT_NAME}" --file "docker-compose.yml" build

docker-compose --compatibility --project-directory . --project-name "${PROJECT_NAME}" --file "docker-compose.yml" up