version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  unit_tests:
    build: .
    # command: pytest --disable-pytest-warnings
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint: "$UNIT_TESTS_ENTRYPOINT"
